name: dummypod

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  husky: ^0.1.7
  lint_staged: ^0.5.1
  melos: ^5.3.0

lint_staged:
  "{apps,packages}/*/{lib,test}/**.dart": dart format --fix
